.github/workflows/ci.yml
=> add github action/runner for ci-cd

tests/mlu/test_fuse_layernorm.py, xpu_graph/passes/patterns/structure/fuse_layernorm.py, xpu_graph/passes/patterns/targets/mlu/structure_replacements.py, xpu_graph/passes/patterns/utils/check_ops.py
* Add: FusedLayerNorm Pattern in passes/patterns/structure/fuse_layernorm.py, with Functional tests in tests/mlu/test_fuse_layernorm.py
* Perf: (Model2) 300+ nodes fused, E2E time -7.4%, MLU -14.8%
=> feat(FuseLayerNorm): fuse handwritten layernorm patterns into F.layer_norm

xpu_graph/__init__.py, xpu_graph/cache.py, xpu_graph/compiler.py, xpu_graph/passes/pass_manager.py
* Add: cache xpu_graph optimized fx graph after common passes
* Perf: reduce warmup time by ~82s for model1 and ~22s for model2; enbale artifact distribution for xpu_graph backends
=> feat(GraphCache): cache xpu_graph optimized fx graph

xpu_graph/__init__.py, xpu_graph/backends/mlu.py, xpu_graph/cache.py, xpu_graph/compiler.py, xpu_graph/config.py, xpu_graph/passes/constant_folding.py, xpu_graph/passes/pass_manager.py, xpu_graph/passes/patterns/common/fold_div.py, xpu_graph/passes/patterns/common/fold_mul.py, xpu_graph/passes/patterns/common/fold_sub.py, xpu_graph/utils.py
* add fold_div/fold_mul/fold_sub
* add a vendor_compiler_config to config, mainly for inductor compile mode. And support "cudagraphs" mode additionally.
* add a "skip_all_passes" flag to config, mainly for debug
=> feat: add some op folders and modify config

xpu_graph/passes/optimizer.py, xpu_graph/passes/patterns/common/fold_mul.py, xpu_graph/passes/patterns/common/fold_sub.py, xpu_graph/passes/patterns/utils/expand_tensor.py
* Bug Description: sub/div folder do something wrong.
* Bugfix: just fix somehow
* logger: move optimizer work log from info to debug
=> fix(op folder): fix some op folder

tests/mlu/test_slice_sum_cat.py, xpu_graph/passes/patterns/targets/mlu/fuse_sum_cat.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_slice_sum_cat.py
1. 增加进入triton的限制，如果slice的范围>1024，退化成小算子模式。
2. 提升triton的性能，在MLU上通过visible cluster起grid，在kernel内部做循环，增强流水。
3. 修复之前的triton kernel 一次load所有tensor数据的bug，只需要load最大的slice范围。
4. model1 提升3% @512batch
=> feat(triton fused_slice_sum_cat): optimized for performance improvement

tests/mlu/test_fuse_slice.py, xpu_graph/passes/patterns/structure/fuse_slice.py, xpu_graph/passes/patterns/targets/mlu/structure_replacements.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_slice.py
【推理】
1. 修复fused_slice在512batch上nram 内存超限的问题
2. 改用tl.make_block_ptr进一步提升性能
3. 增加更多的测例和注释
4. 算子个数不变，360us@512batch。200us@86batch 性能提升40%
=> fix fused slice

.github/workflows/ci.yml, tests/common/test_constant_fold.py, tests/common/test_convert_gelu.py, tests/common/test_fold_cat.py, tests/common/test_fuse_layernorm.py, tests/common/test_register_pattern.py, tests/common/test_remove_layernorm_cast.py
* Fix: change pull targets
* Fix: fix failed tests
=> fix(CI): fix ci settings

tests/mlu/test_fuse_layernorm_mm.py, xpu_graph/passes/patterns/targets/mlu/fuse_layernorm_mm.py
feat(Pattern): add fuse_layernorm_mm Op
* Add: passes/patterns/targets/mlu/fuse_layernorm_mm.py tests/mlu/test_fuse_layernorm_mm.py
* Perf: qianchuan_v2 3394 Op count reduce to 3362
=> feat(Pattern): add fuse_layernorm_mm Op

xpu_graph/passes/patterns/structure/single_continuous_gather.py, xpu_graph/passes/patterns/targets/npu/structure_replacements.py, xpu_graph/passes/patterns/targets/npu/triton_kernel/shortcut_gather.py, xpu_graph/passes/patterns/utils/check_ops.py
feat(Pattern): add continuous gather shortcut pattern
* Add:  gather shortcut pattern,  for continuous index senario, some known bugs to be fixed
* Perf: Model qc GatherOp cost reduced from 0.9ms to 0.015ms
=> sync isolate dev branch

tests/common/test_fuse_matmul.py, xpu_graph/passes/patterns/common/fuse_mm.py
【推理】【训练】
1. 在common中增加addmm算子
2. 在qianchuan训练中可以消除（硬件上）227个kernel
3. 在推理中，图可能先匹配上addmm再匹配上tmo.matmul
=> feat(FusedAddMM): Add mm+add pattern in training.

tests/mlu/test_repeat_to_expand.py, xpu_graph/passes/patterns/targets/mlu/repeat_to_expand.py
1. 将gather前面的repeat转成expand
2. 在512batch上提升4%的性能
=> feat(FusedRepeatToExpand): Convert repeat to expand before gather node

xpu_graph/passes/patterns/targets/mlu/fuse_layernorm_mm.py
=> fix(layernorm_mm): remove print

tests/common/test_constant_fold.py, tests/common/test_cse.py, xpu_graph/compiler.py, xpu_graph/config.py, xpu_graph/passes/constant_folding.py, xpu_graph/passes/optimizer.py, xpu_graph/passes/patterns/targets/mlu/fuse_flash_attention.py, xpu_graph/utils.py
* Add: support user to use ENV variables to adjust compiler's behaviors.
* Add: add some comments to help understanding configures.
* Modified: close xpu_timer to improve log's readability under debug mode.
* Fix: support python3.11
=> feat(config): support user to use ENV variables to adjust compiler's behaviors

tests/mlu/test_fuse_slice_where_cat.py, xpu_graph/passes/patterns/targets/mlu/fuse_slice_where_cat.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_slice_where_cat.py, xpu_graph/passes/patterns/utils/check_ops.py
* Add: fuse_slice_where_cat stack_to_cat
* Perf: Model1 1879 kernel Op count reduce to 1865， Achieved a 1% performance improvement on qianchuan-inference hdtime(without inductor).
=> feat(Pattern): add fuse_slice_where_cat op

xpu_graph/passes/patterns/structure/single_cat.py, xpu_graph/passes/patterns/targets/npu/structure_replacements.py, xpu_graph/passes/patterns/targets/npu/triton_kernel/cat_two_dim.py
* add pattern match conditions for concat
* add cat triton kernel for different input arg num
=> feat(Pattern): Add cat pattern match

xpu_graph/cache.py
* fix: Keep the env variable style with consistent prefix XPUGRAPH
=> fix(Cache): change the env variable from XPU_GRAPH_CACHE_DIR to XPUGRAPH_CACHE_DIR

xpu_graph/passes/patterns/targets/npu/triton_kernel/fused_bmm.py, xpu_graph/passes/patterns/targets/npu/triton_kernel/fused_matmul.py
fix(mm/bmm): fix mm/bmm precision
=> fix(mm/bmm): fix precision

tests/npu/test_sum_bool.py, xpu_graph/backends/passes/npu/sum_bool.py, xpu_graph/passes/patterns/common/fold_reduce.py
** Fix1: Add check for fold_reduce which  will raise error when dims is None instead of List[Int].
** Fix2: Prevent from duplicate registration of pattern_match because it is forbidden by torch.
=> fix(Pattern): fix two bug about sum_bool and fold_reduce

tests/common/test_loop.py, xpu_graph/fx_utils.py
* Bug: unlift changes graph codegen, which disturbs gm signature
* Fix: do not modify the graph codegen in _unlift
=> fix(CodeGen): do not change graph codegen when unlift

xpu_graph/__init__.py, xpu_graph/backends/__init__.py, xpu_graph/compiler.py
fix(adapt-ge): add asend_compiler for deberta module
=> feat(adapt-ge): adapt npu-ge for deberta

xpu_graph/passes/patterns/structure/fuse_slice_cat.py
feat(cat duplication): In fuse_slice_cat, stack is converted to cat. When the cat operation has only one input, it is eliminated.
* Perf: Model A kernel Op count can be optimized down to 33 without inductor
=> feat(cat duplication): Eliminate redundant cat operations

.github/workflows/ci.yml
fix(ci): use new docker images
=> fix(ci): amend ci docker images

xpu_graph/passes/patterns/structure/single_cat.py
*different dtype for memory load
=> Fix(SingleCatTwoDim Pattern): fix memory calculation for type

xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_slice.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/libentry.py
* Add: libentry.py
* Perf: fuse_slice operator can improve host-side performance by 25%
* Accuracy: Both inference and training scenarios have been validated, and the accuracy is  bitwise identical
=> feat(triton kernel): improves host-side performance for triton kernel

xpu_graph/passes/patterns/common/fuse_mm.py
* Perf: ModelA 10851 kernel op count reduce to 10839
=> feat(fuse mm): support mm+view+add fused to addmm+view

xpu_graph/passes/patterns/targets/npu/triton_kernel/cat_two_dim.py
fix(fuse cat):change zeros to empty, reduce 0.1ms
=> fix(fuse cat):change zeros to empty, reduce 0.1ms

tests/mlu/test_fsdp_matmul.py, tests/mlu/test_fuse_layernorm.py, tests/mlu/test_rmsnorm.py, tests/mlu/test_slice_sum_cat.py
=> fix(test mlu): add tocpu in test/mlu

xpu_graph/config.py
=> feat(npu):support multiflow

xpu_graph/config.py
fix(npu config): change flowNum and AicNum from str to int
=> fix(npu config): change flowNum and AicNum from str to int

tests/common/test_fold_squeeze.py, xpu_graph/passes/patterns/common/fold_squeeze.py, xpu_graph/passes/patterns/utils/check_ops.py
=> feat(pattern): add squeeze fold

xpu_graph/__init__.py, xpu_graph/backends/__init__.py, xpu_graph/backends/npu.py, xpu_graph/compiler.py, xpu_graph/config.py, xpu_graph/fx_utils.py, xpu_graph/passes/cse.py
feat(add_ge_backend): support ge compiler
=> Support ge backend

xpu_graph/passes/patterns/structure/single_continuous_gather.py, xpu_graph/passes/patterns/targets/npu/structure_replacements.py
*Bug fix Move the input shape restriction check
in the stage of finding the candidate node
=> fix(SingleContinuousGather): input must be 2d or 3d

xpu_graph/compiler.py, xpu_graph/passes/optimizer.py, xpu_graph/utils.py
* Optimizer will show nodes changing
* Output node statistics before and after xpu_graph
=> feat(log): Add more logs for optimization and debugging

xpu_graph/backends/__init__.py, xpu_graph/backends/ascend.py, xpu_graph/backends/mlu.py, xpu_graph/backends/npu.py, xpu_graph/cache.py, xpu_graph/compiler.py, xpu_graph/fx_utils.py
* feat: the original compiled artifact is not serializable, wrap it with a serialize wrapper
* changed: use compile_fx_inner instead of compile_fx, to generate serializable CompiledFxGraph
=> feat(serializer): implement SerializeWrapper

xpu_graph/fx_utils.py
fix(compat): simplify unnecessary dispatch_export code for compatibility
=> fix(xpu_graph/fx_utils.py): fix the version compatibility of pytorch.

.github/workflows/ci-for-npu.yml
* add .github/workflows/ci-for-npu.yml
=> feat(ci): add ci on npu

tests/mlu/test_slice_sum_cat.py
* Bug description: Precision accumulation causes test cases to fail randomly with large batch sizes.
* Bugfix: Switched initialization from randn to rand and updated precision comparison logic.
=> fix(fuse slice_sum_cat): Precision problem in test case

.github/workflows/ci-for-npu.yml, tests/npu/test_fuse_div_mul_sum.py, tests/npu/test_fuse_permute_sum.py, xpu_graph/__init__.py, xpu_graph/backends/__init__.py, xpu_graph/cache.py, xpu_graph/passes/patterns/targets/__init__.py, xpu_graph/passes/patterns/targets/npu/__init__.py, xpu_graph/passes/patterns/targets/npu/fuse_brc_permute_sum.py, xpu_graph/passes/patterns/targets/npu/fuse_div_mul_sum.py, xpu_graph/passes/patterns/targets/npu/triton_kernel/__init__.py, xpu_graph/passes/patterns/targets/npu/triton_kernel/fused_brc_permute_sum.py, xpu_graph/passes/patterns/targets/npu/triton_kernel/fused_div_mul_sum.py, xpu_graph/passes/patterns/utils/check_ops.py
- Add npu backend registration
- Add two compiler patterns and relative triton kernel
=> feat(NPU compiler) Support Npu for Deberta model

README.md, xpu_graph/compiler.py, xpu_graph/passes/optimizer.py, xpu_graph/utils.py
*logging for difference*
*serialization for graph ir*
=> chore(xpu_graph/utils.py&compiler.py): add difference logging in debug mode.

.github/workflows/ci-for-npu.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, tests/npu/test_fuse_div_mul_sum.py, tests/npu/test_fuse_permute_sum.py, xpu_graph/__init__.py, xpu_graph/backends/__init__.py, xpu_graph/cache.py, xpu_graph/passes/patterns/targets/__init__.py, xpu_graph/passes/patterns/targets/npu/__init__.py, xpu_graph/passes/patterns/targets/npu/fuse_brc_permute_sum.py, xpu_graph/passes/patterns/targets/npu/fuse_div_mul_sum.py, xpu_graph/passes/patterns/targets/npu/triton_kernel/__init__.py, xpu_graph/passes/patterns/targets/npu/triton_kernel/fused_brc_permute_sum.py, xpu_graph/passes/patterns/targets/npu/triton_kernel/fused_div_mul_sum.py, xpu_graph/passes/patterns/utils/check_ops.py
feat(CI): add npu github workflow
feat(pre-commit-config): add python code format
feat(npu-opt): fuse_brc_permute_sum
feat(npu-opt): fused_div_mul_sum
=> feat(npu_compiler): npu compiler opt

tests/mlu/test_fuse_slice.py, tests/mlu/test_fuse_slice_stack_sum.py, xpu_graph/passes/patterns/structure/fuse_slice_stack.py, xpu_graph/passes/patterns/targets/mlu/structure_replacements.py, xpu_graph/passes/patterns/utils/match_sub_list.py
1. 将slice_cat pattern里的expand_transpose_module  pattern 使用小算子拼接而非callfunction
2. 如果是trans+sum， 变成sum
3. 在Model A 推理上消除46op/21kernel, 性能提升5%
=> feat(pattern) add fuse_trans_sum pattern

tests/mlu/test_fuse_mul_sum_cat.py, xpu_graph/passes/patterns/targets/mlu/fuse_mul_sum_cat.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_mul_sum_cat.py
* Add: targets/mlu/triton_kernel/fused_mul_sum_cat.py targets/mlu/fuse_mul_sum_cat.py
* Perf: ModelA can reduce 11 ops with inductor(27 ops without inductor)
=> feat(mulsumcat pattern): add fuse_mul_sum_cat pattern

xpu_graph/passes/patterns/targets/mlu/fuse_mul_sum_cat.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_mul_sum_cat.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_serial_mm_2dot.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_serial_mm_3dot.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_slice.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_slice_sum_cat.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/fused_slice_where_cat.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/get_mlu_devinfo.py, xpu_graph/passes/patterns/targets/mlu/triton_kernel/libentry.py
…icesumcat kernels
* Perf: ModelA hw time improve 1.4%
1.tinyffn grid修改 2.libentry升级 3.手写triton算子控制cluster数量 4.sumcat性能提升
=> feat(triton kernel): performance optimization of the xxxsumcat

tests/mlu/test_combo_slice_where_cat.py, tests/mlu/test_fuse_mul_sum_cat.py, tests/mlu/test_fuse_slice_stack_sum.py, xpu_graph/passes/patterns/targets/mlu/combo_cat_utils.py, xpu_graph/passes/patterns/targets/mlu/combo_slice_where_cat.py, xpu_graph/passes/patterns/targets/mlu/fuse_slice_where_cat.py
1. 将之前用triton写的slice-where-cat替换成 slice-cat-where， slice-cat进一步融合，where留给inductor融合
2. ModelA中，19*slice-where-cat->1*embcat + 19*where
=> feat(combo_slice_where_cat): add combo_slice_where_cat

xpu_graph/config.py
Closes #252
[rules](https://cbea.ms/git-commit/#why-not-how).
- Select one of the following.
- `/tests/common` for `common` tests
- `/tests/mlu` for `MLU` tests
- `/tests/npu` for `GE` tests
- `/tests/ascend` for `acl-graph` tests
- `/tests/xpu_ops` for `xpu-ops` tests
=> feat(config): add  VENDOR_COMPILER_MODE=none to disable inductor

.github/codecov.yml, .github/workflows/ci-for-mlu.yml, .github/workflows/ci-for-npu.yml
Fix the codecov setting for using automatical report-mergence.
Closes #302
=> ci(.github): refine the codecov setting and discard the codecov flags.

.github/workflows/ci-for-mlu.yml, tests/mlu/test_ddp_matmul.py, tests/mlu/test_dist_train_utils.py, tests/mlu/test_fsdp_matmul.py
Closes #287 
* improve ddp&fsdp test cases, select any available port instead of fixed port
* for every run, random select two cards
=> fix(ci): add support for multi-runners

tests/common/test_plugin_pattern.py, xpu_graph/passes/patterns/plugin_pattern.py
literals as inputs through differentiation by users.
Closes #350
=> fix(xpu_graph/passes/patterns/plugin_pattern.py): support rewrite for

.github/workflows/ci-for-mlu.yml, tests/mlu/test_cppwrapper.py, xpu_graph/backends/mlu.py, xpu_graph/passes/patterns/targets/mlu/combo_slice_where_cat.py
=> fix(cpp_wrapper): fix bugs in use torch 2.7

LICENSE.txt, pyproject.toml
=> docs(license): add license

xpu_graph/backends/mlu.py
* won't force overwrite inductor configs
* merge config dict
=> fix(cpp_wrapper_configs): update cpp_wrapper configs

tests/common/test_skip_pat.py, xpu_graph/config.py, xpu_graph/passes/patterns/pattern_manager.py, xpu_graph/utils.py
=> feat(skip_pat): skip specific patterns by config

xpu_graph/compiler.py, xpu_graph/config.py
=> chore(logging): update logging timing
